### ISSUE TITLE
mysql 镜像拉取失败

### ISSUE THREAD

**Issue by m1iktea** [longguikeji/arkid-charts#26]

**Comment by m1iktea** [comment]
values.yaml里面修改mysql镜像后，be服务启动失败
```
mysql:
  enabled: true
  image:
    registry: docker.io
    repository: mysql
    tag: 5.7
    pullPolicy: IfNotPresent
```
<img width="945" alt="微信图片_20220622163854" src="https://user-images.githubusercontent.com/73102617/174984207-d5ca725c-094a-44a1-9d03-a25605eb1346.png">
<img width="522" alt="22" src="https://user-images.githubusercontent.com/73102617/174984450-4dfd8ba7-e777-4536-8e80-cce4073a2573.png">
